### ISSUE TITLE
Memory leak when using TgoBsonSerializer.Deserialize with an invalid json string

### ISSUE THREAD

**Issue by giorgiobazzo** [grijjy/GrijjyFoundation#32] opened 2020-03-03 13:35 UTC
There is a memory leak when using TgoBsonSerializer.Deserialize (AJson, AValue) and AJosn has invalid or badly formatted json content.

I realize this when using:

ReportMemoryLeaksOnShutdown: = True;

at application startup, 

call the procedure Deserialize with an invalid string.

When closing the application I receive the message:

---------------------------
Unexpected Memory Leak
---------------------------
An unexpected memory leak has occurred. The unexpected small block leaks are:

37 - 44 bytes: UnicodeString x 1
53 - 60 bytes: UnicodeString x 1
61 - 68 bytes: UnicodeString x 2
69 - 76 bytes: UnicodeString x 1
77 - 84 bytes: UnicodeString x 2
109 - 116 bytes: UnicodeString x 2
117 - 124 bytes: Unknown x 1

**Comment by neslib** [comment] 2020-03-10 18:16
I cannot reproduce this issue with some invalid JSON documents I tried.
Could you provide a simple test case that shows the issue>

**Comment by giorgiobazzo** [comment] 2020-03-10 20:55
I get it in malformed arrays eg:
JsonString := '{"data_atual":943944444,"abastecidas":0,"bicos":[{"id_bico":16,"status":76,"quantidade":0,"acumulado":0';

See that the end of the array is not correct.

**Comment by giorgiobazzo** [comment] 2020-03-10 21:00
I get it in malformed arrays eg:


  TPABBicoStatus = record
  public
    id_bico: Integer;
    status: Integer;
    acumulado: double;
    quantidade: double;
    procedure Clear;
    function ToJsonString:string;
  end;

  TPABStatus = record
  public
    abastecidas: Integer;
    bicos: TArray<TPABBicoStatus>;
  end;

.....
Result : TPABStatus;
....
  LJson := '{"abastecidas":0,"bicos":[{"id_bico":16,"status":76,"quantidade":0,"acumulado":0';
  TgoBsonSerializer.Deserialize(LJson,Result);

**Comment by erikvanbilsen** [comment] 2020-03-10 22:00
Thanks for the test case. It was useful in pinpointing the issue.
The issue was specific to exceptions that happen during deserialization of a dynamic arrays.
That should be fixed now.

**Closed by erikvanbilsen** 2020-03-10 22:00 UTC

**Comment by giorgiobazzo** [comment] 2020-03-11 12:00
Congratulations on your project, and thank you very much for sharing, it is being very useful in a new project that I am developing.

I needed to work with datetime fields in Unix format (where 1583926427 = GMT: Wednesday, 11 March 2020 11:33:47)

So I added another option called DateTimeUnix to TgoBsonRepresentation, and made some changes to work with this format.
I don't know if I did it in the best way, but I will leave my changes here if you consider it good to include in the next releases:

`  
TgoBsonRepresentation = (Default, Boolean, Int32, Int64, Double, &String,
    DateTime, Document, Binary, ObjectId, Symbol, DateTimeUnix);

...

class procedure TgoBsonSerializer.CheckDateTimeRepresentation(
  const ARepresentation: TgoBsonRepresentation);
begin
  if (not (ARepresentation in [TgoBsonRepresentation.DateTime,
    TgoBsonRepresentation.Document, TgoBsonRepresentation.Int64,
    TgoBsonRepresentation.String, TgoBsonRepresentation.DateTimeUnix ]))
  then
    raise EgoBsonSerializerError.Create('Invalid date/time representation');
end;

...

class function TgoBsonSerializer.DeserializeDateTime(const AInfo: TInfo;
  const AReader: IgoBsonBaseReader): TDateTime;
var
  DT: TgoBsonDateTime;
  Name: String;

  procedure RaiseError;
  begin
    raise EgoBsonSerializerError.Create('Unsupported TDateTime deserialization type');
  end;

begin
  case AReader.GetCurrentBsonType of
    TgoBsonType.DateTime:
      begin
        DT := TgoBsonDateTime.Create(AReader.ReadDateTime);
        Result := DT.ToUniversalTime;
      end;

    TgoBsonType.Document:
      begin
        Result := 0;
        AReader.ReadStartDocument;
        while (AReader.ReadBsonType <> TgoBsonType.EndOfDocument) do
        begin
          Name := AReader.ReadName;
          if (Name = 'DateTime') then
            // Ignore (use Ticks instead)
            AReader.SkipValue
          else if (Name = 'Ticks') then
            Result := goDateTimeFromTicks(AReader.ReadInt64, True);
        end;
        AReader.ReadEndDocument;
      end;

    TgoBsonType.Int64:
      begin
        if AInfo.Representation = TgoBsonRepresentation.DateTimeUnix then
          Result := UnixToDateTime(AReader.ReadInt64, True)
        else
          Result := goDateTimeFromTicks(AReader.ReadInt64, True);
      end;

    TgoBsonType.String:
      Result := ISO8601ToDate(AReader.ReadString, True);

    TgoBsonType.Int32:
      if AInfo.Representation = TgoBsonRepresentation.DateTimeUnix then
        Result := UnixToDateTime(AReader.ReadInt32, True)
      else
        RaiseError;

  else
    RaiseError;
  end;
end;

...

class procedure TgoBsonSerializer.SerializeDateTime(const AInfo: TInfo;
  const AValue: TDateTime; const AWriter: IgoBsonBaseWriter);
var
  MS: Int64;
  S: String;
begin
  if (AInfo.IgnoreIfDefault) and (AValue = 0) then
    Exit;

  if (AInfo.Name <> '') then
    AWriter.WriteName(AInfo.Name);

  case AInfo.Representation of
    TgoBsonRepresentation.DateTime:
      begin
        MS := goDateTimeToMillisecondsSinceEpoch(AValue, True);
        AWriter.WriteDateTime(MS);
      end;

    TgoBsonRepresentation.Document:
      begin
        MS := goDateTimeToMillisecondsSinceEpoch(AValue, True);
        AWriter.WriteStartDocument;
        AWriter.WriteDateTime('DateTime', MS);
        AWriter.WriteInt64('Ticks', goDateTimeToTicks(AValue, True));
        AWriter.WriteEndDocument;
      end;

    TgoBsonRepresentation.Int64:
      AWriter.WriteInt64(goDateTimeToTicks(AValue, True));

    TgoBsonRepresentation.String:
      begin
        S := FormatDateTime('yyyy-mm-dd"T"hh:nn:ss', AValue, goUSFormatSettings);
        MS := MilliSecondOf(AValue);
        if (MS <> 0) then
          S := S + '.' + IntToStr(MS * 10000);
        AWriter.WriteString(S);
      end;

    TgoBsonRepresentation.DateTimeUnix:
      AWriter.WriteInt64(DateTimeToUnix(AValue, True));

  else
    Assert(False);
  end;
end;

...

procedure TgoBsonSerializer.TVarInfo.GetSerializationProcs(
  const AType: PTypeInfo);
var
  TypeData: PTypeData;
begin
...
    tkFloat:
      begin                                           //to be able to use a default value in unix format						
        if FIgnoreIfDefault and FHasDefaultValue and (FRepresentation <> TgoBsonRepresentation.DateTimeUnix)  then
          raise EgoBsonSerializerError.Create('Custom default values are not supported for floating-point types');

...
end;


procedure TgoBsonSerializer.TPropertyInfo.GetSerializationProcs(
  const AType: PTypeInfo);
var
  TypeData: PTypeData;
begin
...

    tkFloat:
      begin                                          //to be able to use a default value in unix format
        if FIgnoreIfDefault and FHasDefaultValue and (FRepresentation <> TgoBsonRepresentation.DateTimeUnix) then
          raise EgoBsonSerializerError.Create('Custom default values are not supported for floating-point types');

..
end;
`
